# Generated by Django 4.2.7 on 2024-04-25 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_teamlead',
            field=models.BooleanField(default=False),
        ),
    ]
